### ISSUE TITLE
Lots of extra cruft in releases

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#10]
![screen shot 2018-09-05 at 10 32 04 am](https://user-images.githubusercontent.com/1568662/45107594-4c668d00-b0f7-11e8-9593-7a8cdf529d38.png)

- 125MB -> frameworks (electron, etc); can't lose that!
-    7MB -> `app/build` - can't lose that! (green square)
- 133MB -> `node_modules` (red square)
  - Much of this is dev dependencies - babel, jest, eslint, webpack, etc...
  - Some could be filtered with `--ignore`
  - ...and maybe some packages moved from `dependencies` to `devDependencies` ?
- 22MB -> `app/assets/images`  (yellow square)
  - Just screenshots used in the README - could probably be added to `--ignore` 

Anyways, by moving some packages around and getting crazy with `--ignore`, could probably cut the release size in half... if you're interested I can help out with some of that, but feel free to close if you don't care that much about release size - after all, I'm installing this on a 1TB HD :p

**Comment by sandiz** [comment]
i prefer lean apps so this change would be welcome! feel free to take a look, i'll do the same and see what else can be removed.

**Comment by sandiz** [comment]
i'm working on removing `app/assets/images` and `src/tools/RockSniffer` (mac only) from builds

**Comment by JustinAiken** [comment]
> i'm working on removing  ... src/tools/RockSniffer (mac only) from builds

Although if you manage to get that working, it would be awesome 😀

**Comment by JustinAiken** [comment]
> what app did you use to generate the graph ?

[GrandPerspective](http://grandperspectiv.sourceforge.net/)

**Comment by sandiz** [comment]
fixed in #11
