### ISSUE TITLE
Doesn't Load / Blank Window

### ISSUE THREAD

**Issue by dgoad95** [sandiz/rs-manager#103]
![2020-05-17 21_34_21-Stats Manager for Rocksmith](https://user-images.githubusercontent.com/9425216/82166368-3d514f80-9886-11ea-981a-b46c4f070396.png)
Upon loading, window is blank. For a few frames, it looks like you can see something on the left hand side, but it quickly disappears.

Effects current version at minimum, potentially effects others as well.

**Comment by dgoad95** [comment]
Affects version 3.0.0 as well it seems...AMD GPU on Windows 10.

Until the window is activated, you're able to click on the navigation bar below the Title Bar.
![2020-05-17 21_40_34-Stats Manager for Rocksmith](https://user-images.githubusercontent.com/9425216/82166702-47c01900-9887-11ea-9b4e-c32391ba5d14.png)

If I Toggle Developer Tools, it tells me Javascript needs to be enabled -- where might that be?
![2020-05-17 21_41_57-Doesn't Load _ Blank Window · Issue #103 · sandiz_rs-manager](https://user-images.githubusercontent.com/9425216/82166741-61f9f700-9887-11ea-970d-1f94cda58c16.png)

**Comment by sandiz** [comment]
hi @dgoad95, can you share the screenshot of the developer tools with the console tab selected

![image](https://user-images.githubusercontent.com/5438703/82273251-d5f0d980-9931-11ea-922b-d8ba08dde928.png)

in the meantime i'll check if the windows app is working on my end or not

**Comment by sandiz** [comment]
also have you tried the latest build v3.0.11 released yesterday

**Comment by dgoad95** [comment]
I did try it, as I said above. When I use the new version, I don't see the ribbon to select Developer Tools, as the first screenshot shows, unless you've got a hotkey for that.

Here is the screenshot you requested. I can't imagine it'll be much help since it's not of the latest version.

As I said, if you have a hotkey for opening the Developer Tools, I'll gladly check. Otherwise, I cannot access them.

![2020-05-18 21_40_56-Stats Manager for Rocksmith](https://user-images.githubusercontent.com/9425216/82275274-4ad30c00-9950-11ea-86e0-725dd35aebfb.png)

**Comment by dgoad95** [comment]
Here is a video: https://drive.google.com/open?id=1b58uNIpYPRZ7_tvaifTdPckWWacaj7pr

If you can advance it frame by frame, you can see that it tries to do *something* before blinking out of existence forever:

![2020-05-18 21_52_32-2020 05 18-21 43 mp4 ‎- Photos](https://user-images.githubusercontent.com/9425216/82275968-ff216200-9951-11ea-8698-546b2e6b6933.png)

**Comment by sandiz** [comment]
thanks for the info @dgoad95, i need one more favor, will you be able to click on the [2.aa558089.chunk.js:1] and share the screenshot of the console (it should show the code its crashing at). That should help me narrow down the issue

![image](https://user-images.githubusercontent.com/5438703/82281852-40f8db00-9947-11ea-931d-02ce858da12a.png)

> As I said, if you have a hotkey for opening the Developer Tools

i think its ctrl+shift+i on windows 

thanks for helping me debug this :-)

**Comment by dgoad95** [comment]
when i double click on that, it takes me to a file that's 65k lines long, but when i hit the "pretty print" button at the bottom of the panel, i get this:

    var ms = "function" === typeof WeakSet ? WeakSet : Set;
    function gs(e, t) {
        var n = t.source
          , r = t.stack;
        null === r && null !== n && (r = J(n)),
        null !== n && $(n.type),
        t = t.value,
        null !== e && 1 === e.tag && $(e.type);
        try {
            **_console.error(t)_**
        } catch (i) {
            setTimeout((function() {
                throw i
            }
            ))
        }
    }

I was able to get the console to pop up without the ribbon being selectable -- apparently my PC has ctrl + shift + i bound to screenshot, so with that disabled it pops up. there are a few more errors with the latest build.

![2020-05-19 09_04_44-Stats Manager for Rocksmith](https://user-images.githubusercontent.com/9425216/82330473-e5fbce00-99b0-11ea-9dd7-486d9256a079.png)

in this image, 2.3dc7401f.chunk.js:2 TypeError: Cannot read property 'length' of null takes you to the same place as the highlighted line in the screenshot above.

**Comment by dgoad95** [comment]
looks like the error that says EADDRINUSE is because I had two open at the same time and didn't realize. So i'm not certain if any of that is usable. 

![2020-05-19 09_42_31-Stats Manager for Rocksmith](https://user-images.githubusercontent.com/9425216/82334201-a84d7400-99b5-11ea-866b-7e996cb70a4b.png)

2.3dc7401f.chunk.js:2 takes you to the same place as the snippet above.

**Comment by sandiz** [comment]
perfect thanks so much, working on a fix...

**Comment by sandiz** [comment]
looks like its failing to find the steam profile. you can workaround this issue by manually setting the `prfldb` and `steamID` (optional) fields in the `config.json` found in `%APPDATA%/Roaming/rs-manager`

you can find your prfldb in your `steam/userdata/<random number>/221680/remote` folder. the file ends with _prfldb,

![image](https://user-images.githubusercontent.com/5438703/82379197-5c152a80-99db-11ea-81b7-f8338f52b2f2.png)

here's my config.json for reference
```json
{
    "prfldb": "d:\\program files (x87)\\steam\\userdata\\25347454\\221680\\remote/0976B41EC00D496F9F4214AA2C752700_PRFLDB",
    "steamLoginSecure": "",
    "showScoreAttack": true,
    "useCDLCinStats": true,
    "scoreAttackDashboard": [true, true, true, true],
    "sessionID": "",
    "masteryThreshold": 0.95,
    "showPSStats": false,
    "dateFormat": "hm",
    "dateSrc": "rs",
    "steamID": "",
    "state": {
        "sidebar": {
            "tab-songs": true,
            "tab-setlist": false,
            "folder_starred": true,
            "folder_custom_1542342073": true
        }
    },
    "steamAPIKey": "",
    "defaultSortOption": [{
        "label": "mastery-desc",
        "value": "mastery-desc"
    }],
    "pathToImportRSM": "C:\\Python\\Scripts\\importrsm.exe",
    "showSetlistOverlayAlways": false,
    "isSudoWhitelisted": false,
    "currentZoomFactor": 0.9
}
```

Let me know if that works! In the meantime i am prepping a build with the fix

**Comment by sandiz** [comment]
uploaded a build [v3.0.12](https://github.com/sandiz/rs-manager/releases/tag/v3.0.12) that might fix the issue. give it a go when you can!

thanks again for all the help!

**Comment by dgoad95** [comment]
Either the new version fixed it, or manually editing the config file did.

My \\remote folder actually had two of those _prfldb files. The first one didn't work, but the second one did (on version 3.0.11) after downloading 3.0.12, it comes up no problem -- so either the config change is still active, or the new version took care of it.

Thanks for investigating. I'm curious to see how much I suck at Rocksmith ;)

**Comment by sandiz** [comment]
thanks for confirming, closing this issue as fixed
