### ISSUE TITLE
Stats refresh when using Rocksmith Live

### ISSUE THREAD

**Issue by GeePee29** [sandiz/rs-manager#104]
I'm not sure if this is actually s bug, but when playing using Rocksmith Live the stats refresh is being triggered several times (4-5) a minute.

I am using v3.0.12

**Desktop (please complete the following information):**
 - OS: W10
 - Browser firefox

It's not the end of the world, but it is distracting when you are trying to concentrate.
TIA

**Comment by sandiz** [comment]
thanks for the report, i think i can suppress that..

**Comment by sandiz** [comment]
hmm looks like i was already [suppressing](https://github.com/sandiz/rs-manager/blob/master/src/Components/rsliveView.js#L900) that.. do you have a screenshot by any chance ?

was it the toaster or the banner text up top that keeps getting triggered ?

**Comment by GeePee29** [comment]
Stats update windows pops up in the bottom right hand corner of the screen.
Disappears after a few seconds.

**Comment by sandiz** [comment]
can you give [v3.0.13](https://github.com/sandiz/rs-manager/releases/tag/v3.0.13) a try and see if it fixes the issue...

**Comment by GeePee29** [comment]
All OK now. No popup stats window when playing in Rockstar Live with
tracking turned on but stats are still updating OK at the end of playing a
song.
Thanks for fixing.

**Comment by sandiz** [comment]
sweet thanks for confirming! closing the issue
