### ISSUE TITLE
Saving Setlist as JSON file does not work. No error message shown

### ISSUE THREAD

**Issue by Rakshasas** [sandiz/rs-manager#116]
**Describe the bug**
When exporting a set list and having **JSON** selected and then clicking **Start Export** opens a file save prompt, but it will not actually save the file. However, the correct file name will appear in the *recents files* list in Windows File Explorer, implying some kind of attempt was made. Hovering over the file shows 0 bytes and it is not actually in that directory at all.

**To Reproduce**
1. Create a new Setlist
1. Rename the set list to something simple, such as "TEST"
1. Add songs to the set list, for example: "Pearl Jam" as a generated filter
1. Click **Export** button
1. Change Drop down value to **JSON**
1. Click **Start Export**
1. Save as prompt should appear. Navigate to a simple directory, such as C:\Temp and save *Test_export.json*
1. Click **Save** if you have not already done so

**Expected behavior**
Some sort of confirmation that the file was saved (similar to when Rocksmith Song List) and of course the file appearing in the save location with data.

**Actual behavior**
Save as dialog disappears, no confirmation of the save being completed occurs. File does not appear in C:\Temp but there is an entry now in the Recent Files list in Windows File Explorer with the file name used. Hovering over the file will create a tooltip indicating that the file is 0 bytes. Right-clicking and selecting *Open File Directory* navigates you to the correct location, but the file is not present at all.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Rocksmith Manager Version 3.0.13

**Comment by sandiz** [comment]
looking into this, thanks for the detailed bug description!

**Comment by Rakshasas** [comment]
Awesome! Thank you!

**Comment by sandiz** [comment]
let me know if [v3.0.14](https://github.com/sandiz/rs-manager/releases/tag/v3.0.14) fixes the issues, pls reopen if not 🙏

**Comment by Rakshasas** [comment]
Yup, exported the setlist as json. 

Thanks :)
