### ISSUE TITLE
Cannot filter out bonus/alternate arrangements

### ISSUE THREAD

**Issue by snard6** [sandiz/rs-manager#119]
I can't seem to find a way to filter out the Bonus/Alternate arrangements. It appears like the right way to do this would be with the "Arrangement" filter type. But when I type either of those into it it doesn't appear to work. Digging into the code it looks like the field may only look for the following values: ["lead", "rhythm", "bass", "combo"].

Is it possible to filter out those arrangements in a setlist?

**Comment by snard6** [comment]
I created a pull request that does this:
https://github.com/sandiz/rs-manager/pull/120

**Comment by sandiz** [comment]
fixed with #120
