### ISSUE TITLE
[Feature] - CDLC support

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#14]
What do you think about...

- Adding a `is_custom` type field to the DB
- On the psarc explorer, add a checkbox when you import a song for "is custom"
- On songlist view, color custom songs different or some other visual indicator
- On the dashboard view, have a toggle to include customs, or limit to official content for all stat calculations

**Comment by sandiz** [comment]
👍, sounds useful, i have ton of cdlc. i'll start working on it!

**Comment by sandiz** [comment]
Fixed in release  [v0.8.0](https://github.com/sandiz/rs-manager/releases/tag/v0.8.0)

Label CDLC via PSARC Explorer
![image](https://user-images.githubusercontent.com/5438703/45915538-541e7500-be0b-11e8-9ca8-d91c3d403cd9.png)

or via Song Details
![image](https://user-images.githubusercontent.com/5438703/45915546-70221680-be0b-11e8-9de9-400dc564bcba.png)

**Comment by sandiz** [comment]
Dashboard stats can now ignore cdlc (via Settings)
![image](https://user-images.githubusercontent.com/5438703/45915558-ac557700-be0b-11e8-8e1b-b8c7136c8521.png)

**Comment by sandiz** [comment]
Feel free to open issues for feedback/bugs!

**Comment by JustinAiken** [comment]
Imported a packed .psarc with ~50 some odd songs, and checked the `Mark All as CDLC` - half of them ended up marked `is_cdlc` and half didn't... 

Cleared them all out of the sqlite3 DB manually, will try adding again to see if it's reproducible..

**Comment by sandiz** [comment]
can reproduce, fixed in [v0.8.1](https://github.com/sandiz/rs-manager/releases/tag/v0.8.1). could you pls verify when you get a chance

**Comment by JustinAiken** [comment]
> can reproduce, fixed in v0.8.1. could you pls verify when you get a chance

Confirmed fixed! ✅
