### ISSUE TITLE
Need Screenshot for Score Attack Stats

### ISSUE THREAD

**Issue by sandiz** [sandiz/rs-manager#17]
Hi @JustinAiken, can you share screenshots of your Score Attack Stats. I would like to update the readme with it if its ok

thanks!

**Comment by JustinAiken** [comment]
Sure, here's a few to choose from:

![screen shot 2018-09-24 at 8 04 04 am](https://user-images.githubusercontent.com/1568662/45956685-757c8e00-bfd0-11e8-9592-fa4037d83026.png)

![screen shot 2018-09-24 at 7 51 51 am](https://user-images.githubusercontent.com/1568662/45956690-77dee800-bfd0-11e8-80e2-f0b20177ae4f.png)

![screen shot 2018-09-24 at 7 52 23 am](https://user-images.githubusercontent.com/1568662/45956721-84634080-bfd0-11e8-9f3b-65d4f107d913.png)

![screen shot 2018-09-24 at 7 52 14 am](https://user-images.githubusercontent.com/1568662/45956744-91802f80-bfd0-11e8-9719-655e77b99166.png)
