### ISSUE TITLE
Some thoughts about scores

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#18]
- In the songlist view, songs with a mastery above 100 (like 105% from Master mode) show up as 100% - what about showing it as 105? Still keeping the bar the same though

- Instead of hardcoding 95% as "mastered"
  - https://github.com/sandiz/rs-manager/blob/f9310b2b5d9b293002ee331d5911c9468f4cfabf/src/sqliteService.js#L403
  - Could that be user-configurable? 

- For the LAS stat tables, there's 3 bars now, plus one unplayed
  - But the SA stat tables has 6 bars, plus one unplayed
  - So could expand the LAS ranges to also have 6, and then the stat tables would be the same height
  - Maybe something like "100+", "95-99.99", "90-95", "80-90", "70-80", "0-70"

Thoughts on each of these?

**Comment by sandiz** [comment]
> like 105% from Master mode

yup master mode was always a TODO item for me

> 95% as "mastered"

> could expand the LAS ranges to also have 6,

👍

**Comment by sandiz** [comment]
added support for all these in `v0.9.2`. Let me know if you have any feedback
