### ISSUE TITLE
[Feature Request] Score Attack

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#2]
This thing is amazing!

Would also be nice if:
- Song views had "SA Hard" next to mastery, so one can see songs that are 100% mastered but only Gold SA'd, etc..
- Dashboard view had a SA Hard breakdown for songs similar to Lead/Rhythm/Bass, showing count unplayed, count failed, count gold'd, count platinum'd, etc

**Comment by sandiz** [comment]
Hi @JustinAiken,

SA stats is a great idea! I took a look the player data and implementing what you suggest should be straightforward. Will take a crack over the weekend.

Thanks for finding the app useful! 😃

**Comment by JustinAiken** [comment]
If it helps, here's how I parse that out (in Ruby, but reading json is reading json).. ->

- This data ripped from the raw JSON https://github.com/JustinAiken/rsgt/blob/d374b7797239b18d36a4c3cd8c7326ddd5ca003e/lib/rsgt/saved_game/score_attack/song.rb#L17-L25 
- feeds into this kind of thing: https://github.com/JustinAiken/rsprogress_client/blob/02b1d246d466ed7187c7572dc83fe83c2ae4afce/lib/progress_ripper.rb#L82-L95 


- All that is under the `SongsSA` key, which is parallel to the `Songs` key you're using now to get mastery 
- It doesn't keep track of percentages (no way to see if you got 100% or not)
- It doesn't keep track of playcount-per-difficulty

**Comment by sandiz** [comment]
thanks @JustinAiken for the pointers. 
Score attack stats should now be available in `alpha4` release. let me know how it works!

**Comment by sandiz** [comment]
(I don't play SA that often so i dont have much stats, pls share yours! )
![Screenshot](https://github.com/sandiz/rs-manager/raw/master/assets/images/songs.owned.png)

**Comment by JustinAiken** [comment]
>  me know how it works!

It works! Although you have to do "update Mastery from RS Profile" on the Songs page to get the SA stats on the dashboard to refresh

>  i dont have much stats, pls share yours

![screen shot 2018-07-23 at 9 33 46 am](https://user-images.githubusercontent.com/1568662/43088516-91b510c6-8e5f-11e8-973e-ac349c6a98e4.png)

![screen shot 2018-07-23 at 9 33 20 am](https://user-images.githubusercontent.com/1568662/43088522-94e9d90c-8e5f-11e8-9c10-e5e0965d2b2f.png)

> Please reopen or create a new issue if you have any suggestions! 

- I'd suggest separating out the SA by difficulty levels; right now getting a bronze on Master will hide a platinum on Hard, etc..
- Also for the dashboard counts
  - Instead of a raw number of plats/golds/etc, break it down - have a "Score Attack Hard", "Score Attack Master" section
  - And also include "Unplayed" there like there is for the arrangement breakdowns

**Comment by sandiz** [comment]
thanks for the great feedback and screenshots!
three things to fix:
1. dashboard refresh button should refresh SA stats in dashboard view
2. badges by difficulty in songs view
3. add score attack hard and score attack master sections in dashboard view

**Comment by sandiz** [comment]
hi @JustinAiken, how does these look (stats are fake) .. do they convey all the information you want ?

Dashboard - plat/gold/silver rankings per hard/master
![ss](https://content.screencast.com/users/sandic1/folders/Jing/media/9f12e235-1010-4907-8f2d-d9326f35c471/00000175.png)

Songs Owned - all badges will now be shown with more details on hover
![ss](https://content.screencast.com/users/sandic1/folders/Jing/media/9e20e8d2-7d09-4cf5-8ef5-0b16fe8df35d/00000176.png)

**Comment by JustinAiken** [comment]
Very nice!

**Comment by sandiz** [comment]
thanks for the feedback, 

fixed in [`alpha4.1`](https://github.com/sandiz/rs-manager/releases/tag/alpha4.1)

**Comment by JustinAiken** [comment]
2 minor issues -

- It shows `0` for various SA Master counts, even though I do have some
  - ... SA Hard counts seems legit
- Not all the levels fit 
  - through silver does
  - but bronze/failed are cut off

![screen shot 2018-07-27 at 5 05 26 pm](https://user-images.githubusercontent.com/1568662/43349772-66a36d70-91bf-11e8-85eb-f9247b7a3025.png)

![screen shot 2018-07-27 at 5 06 56 pm](https://user-images.githubusercontent.com/1568662/43349782-7f6bd284-91bf-11e8-835a-be70b8b8d673.png)

**Comment by sandiz** [comment]
hi @JustinAiken, thanks for the feedback

fixed in [alpha5.1](https://github.com/sandiz/rs-manager/releases/tag/alpha5.1)
>It shows 0 for various SA Master counts, even though I do have some

SA Master should now show stats correctly. (my stats are 0 on master so i didnt notice anything wrong earlier 😛)
Fixed the SA Badge tooltip position, it should now be positioned correctly next to the badge you hover when you scroll instead of getting cut off. 

> Not all the levels fit
Are you talking about the high score being truncated in the tool tip?

**Comment by JustinAiken** [comment]
> SA Master should now show stats correctly. 

They do! I don't have *much* more than you, but the handful of master picks now show up

![screen shot 2018-07-28 at 2 16 50 pm](https://user-images.githubusercontent.com/1568662/43360328-ebe8992c-9270-11e8-9479-7353b47f06fa.png)

> Fixed the SA Badge tooltip position, it should now be positioned correctly next to the badge you hover when you scroll instead of getting cut off.

Oh nice, I hadn't even noticed that one.. 

> > Not all the levels fit

> Are you talking about the high score being truncated in the tool tip?

No, I mean on the dashboard, where it shows the counts - as you seen in the screen shot, Plat/Gold/Silv/Unplayed all fit, but you can't see Bronze/Failed counts - problem remains in alpha 5.1

**Comment by sandiz** [comment]
oh i see what you mean, i'll add bronze/failed counts

just to clarify, failed counts are arrangements which have playcount > 0 but no badges right ?

**Comment by JustinAiken** [comment]
> just to clarify, failed counts are arrangements which have sa playcount > 0 but no badges right ?

Not quite - Under `Badges`/difficulty it's:
- unplayed is `0.0`
- "failed" is `1.0`
- bronze is `2.0`
- silver is `3.0`
- gold is `4.0`
- plat is `5.0`

So a failed song would look like

```ruby
{
  ...
  <random identifier>: {
     ..
     "Badges": {
        "Easy": 0.0 # Unplayed
        "Medium": 0.0 # Unplayed
        "Hard": 5.0 # Platinum
        "Master": 1.0 # Fail!
  }
}
```

**Comment by sandiz** [comment]
fixed in [alpha5.2](https://github.com/sandiz/rs-manager/tree/alpha5.2)

let me know if the bronze/failed count look correct

**Comment by JustinAiken** [comment]
Perfect!

![screen shot 2018-07-29 at 1 06 38 pm](https://user-images.githubusercontent.com/1568662/43369741-434a379c-9330-11e8-977a-59e13b5ec2ac.png)

Counts match what my [own tool](https://github.com/JustinAiken/rsprogress_server) show!

**Comment by sandiz** [comment]
great work on `rsprogress_server`! thanks for sharing, lot of neat things i learnt/can learn from your implementation! 😇
