### ISSUE TITLE
Software doesn't load, stay on a white screen

### ISSUE THREAD

**Issue by Firekorn** [sandiz/rs-manager#22]
Note sure what kind of information i could share just like that.

Windows 10 1803-17134.345

One detail is that the tool isn't in the same place as the game (no idea if that matters) and i got version 1.0.2

Tried the version 1.0.0 and it loads perfectly until i load a profile and then i just get the background image but nothing else.

**Comment by JustinAiken** [comment]
Try toggling on the developer tools (on mac it's Apple+Shift+I, not sure the combo on Windows), and in the console tab see if there's any errors you can screenshot..

**Comment by Firekorn** [comment]
On version 1.0.0 i get this after trying to load a profile : 
sqliteService.js:575 Uncaught (in promise) TypeError: Cannot read property 'get' of null
    at sqliteService.js:575
    at w (runtime.js:62)
    at Generator._invoke (runtime.js:288)
    at Generator.e.(anonymous function) [as next] (file:///G:/RS%20manage/resources/app/build/static/js/1.a36725f0.chunk.js:1:453254)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at ua (sqliteService.js:573)
(anonymous) @ sqliteService.js:575
w @ runtime.js:62
(anonymous) @ runtime.js:288
e.(anonymous function) @ runtime.js:114
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
ua @ sqliteService.js:573
ia @ sqliteService.js:573
(anonymous) @ settingsView.js:242
w @ runtime.js:62
(anonymous) @ runtime.js:288
e.(anonymous function) @ runtime.js:114
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
t @ settingsView.js:84
Qi @ react-dom.production.min.js:3323
no @ react-dom.production.min.js:3507
Ao @ react-dom.production.min.js:4486
Ro @ react-dom.production.min.js:4505
pa @ react-dom.production.min.js:4826
da @ react-dom.production.min.js:4800
ba @ react-dom.production.min.js:5202
Dn @ react-dom.production.min.js:1737
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
t @ settingsView.js:84
Qi @ react-dom.production.min.js:3323
no @ react-dom.production.min.js:3507
Ao @ react-dom.production.min.js:4486
Ro @ react-dom.production.min.js:4505
pa @ react-dom.production.min.js:4826
da @ react-dom.production.min.js:4800
ba @ react-dom.production.min.js:5202
Dn @ react-dom.production.min.js:1737
configService.js:28 creating empty config file
react-dom.production.min.js:3744 TypeError: Cannot read property 'basename' of undefined
    at t.a.render (settingsView.js:393)
    at $i (react-dom.production.min.js:3357)
    at Qi (react-dom.production.min.js:3348)
    at no (react-dom.production.min.js:3507)
    at Ao (react-dom.production.min.js:4486)
    at Ro (react-dom.production.min.js:4505)
    at pa (react-dom.production.min.js:4826)
    at da (react-dom.production.min.js:4800)
    at ba (react-dom.production.min.js:5202)
    at Dn (react-dom.production.min.js:1737)
so @ react-dom.production.min.js:3744
n.callback @ react-dom.production.min.js:4018
ai @ react-dom.production.min.js:2666
oi @ react-dom.production.min.js:2654
ha @ react-dom.production.min.js:5090
pa @ react-dom.production.min.js:4826
da @ react-dom.production.min.js:4800
ba @ react-dom.production.min.js:5202
Dn @ react-dom.production.min.js:1737
react-dom.production.min.js:4817 Uncaught TypeError: Cannot read property 'basename' of undefined
    at t.a.render (settingsView.js:393)
    at $i (react-dom.production.min.js:3357)
    at Qi (react-dom.production.min.js:3348)
    at no (react-dom.production.min.js:3507)
    at Ao (react-dom.production.min.js:4486)
    at Ro (react-dom.production.min.js:4505)
    at pa (react-dom.production.min.js:4826)
    at da (react-dom.production.min.js:4800)
    at ba (react-dom.production.min.js:5202)
    at Dn (react-dom.production.min.js:1737)

On version 1.0.2 i can't get the console to show up at all, even the background image doesn't show up at all.

**Comment by sandiz** [comment]
Thanks for the report and stack trace @Firekorn , investigating..

**Comment by Firekorn** [comment]
Didn't had any issue apparently and here is a screenshot of the console : 
https://imgur.com/onhUqlW

**Comment by sandiz** [comment]
thanks for confirming! closing issue

let me know if you have any more feedback/issues

**Comment by sandiz** [comment]
console looks good, though decrypt profile is tad high. Whats the file size of your prfldb, wondering if its just too many stats

**Comment by Firekorn** [comment]
Profile is 1,1Mb large and i have tons or score linked to no psarc as i test a lot of CDLC that i don't keep in my DLC folder.
