### ISSUE TITLE
List filtering

### ISSUE THREAD

**Issue by Firekorn** [sandiz/rs-manager#23]
So i've used it a little and one thing that i would like to be able to manage is to filter out the listing in the "songs owned" (might probably be worth to all listing but this the one i've used at the moment).

For example, i wanted to complete alt/bonus arrangement in SA that i haven't done yet but the only thing i could use was to sort by Badges and i couldn't then make it so it's ordered by tuning (or maybe filter out bass if i wanted to do guitar only).

I know some of it is doable using the search (for reducing the arrangement type) but it's a bit limited.

**Comment by JustinAiken** [comment]
Hey, that's really useful!

Some other filters that would kill:
  - If tunings had `Any standard` or `Any drop` or `Any Nonstandard`... 
     (Just doing `E Standard` `OR` `D Standard` etc doesn't work, because I just want to `OR` the tunings, not the rest of the conditions) 
  - If there was a "440 standard" option you could set or unset
  - If there was a capo/no capo filter 
  - SA Hard badge >= Gold/Plat/FC/etc
(I could PR some of these probably if you like)

**Comment by sandiz** [comment]
pr's welcome! let me know which ones you are handling, i can handle the others

**Comment by Firekorn** [comment]
I didn't imagine that setlist could have been generated automatically, nice to know.

Will have to play around with it :)

**Comment by JustinAiken** [comment]
> SA Hard badge >= Gold/Plat/FC/etc

I'll grab this one

**Comment by sandiz** [comment]
> If tunings had Any standard or Any drop or Any Nonstandard...
> (Just doing E Standard OR D Standard etc doesn't work, because I just want to OR the tunings, not the rest of the conditions)
> If there was a "440 standard" option you could set or unset
> If there was a capo/no capo filter

added in [1.0.5](https://github.com/sandiz/rs-manager/releases/tag/v1.0.5)
