### ISSUE TITLE
Tuning sorting

### ISSUE THREAD

**Issue by Firekorn** [sandiz/rs-manager#28]
At the moment, when sorting by tuning the listing is not consistent at all.

Capo and off tuned song just randomly in the middle of other song in the same tuning :
https://imgur.com/IrQZwGR

And listing that doesn't correspond to tuning order in RS which doesn't help quickly noticing where you are : 
https://imgur.com/f4DWFv7

Would be nice if it was more consistent with RS own sorting.

**Comment by sandiz** [comment]
> correspond to tuning order in RS 

i took a look at RS tunings and it looks like its ordered like so (ignore the other number)
["E Standard", 0]
["Drop D", 2]
["Open E", 5]
["Open A", 6]
["Eb Standard", 6]
["Eb Drop Db", 8]
["D Standard", 12]
["D Drop C", 14]
["C# Standard", 18]
["C# Drop B", 20]
["C Standard", 24]
["B Standard", 30]
["B Drop A", 32]

above is the order you meant, right ? @Firekorn

**Comment by Firekorn** [comment]
Yeah, though that doesn't list all the custom tuning that can exist but at least getting them to sort in a more logical manner would be a nice first step :)

**Comment by sandiz** [comment]
fixed in [v1.2.3](https://github.com/sandiz/rs-manager/releases/tag/v1.2.3)

when you first open this version, you might see a "Updating tuning weights.." message if you have a lot of songs. once it finishes, you should be able to sort by tunings properly

let me know if you have more feedback!

**Comment by sandiz** [comment]
> Capo and off tuned song just randomly in the middle of other song in the same tuning :
https://imgur.com/IrQZwGR

this can be fixed by adding a Capo filter and setting it to false
