### ISSUE TITLE
Some general problems

### ISSUE THREAD

**Issue by Zoutje** [sandiz/rs-manager#29]
Hi there,

Zoutje here. I really liked the design of the app and its looking awesome. Unfortunately I can't get it to work.

I got a few issues:
-I can't select a control path.
-Whenever I change the rocksmith profile (_prfldb:) it goes blank like here;
https://i.imgur.com/OUBW1I7.png
-The sign in through Steam button does nothing for me.

Would love to use this app as I am a dedicated RS player and this would be really nice to keep track of everything.

Friendly greetings,

Zoutje

**Comment by sandiz** [comment]
thanks for the report, investigating!

**Comment by sandiz** [comment]
> -I can't select a control path.

what do you mean by control path ?

**Comment by sandiz** [comment]
pushed a bunch of fixes [here](https://github.com/sandiz/rs-manager/releases/tag/v1.1.1).

can you try the following steps and let me know if you see any errors 

- remove or rename rs-manager from %appdata% folder (type %appdata% in Windows->Run to open folder)
- download and unzip v1.1.1
- start rs-manager, go to settings, add your prfldb and save settings
- go to psarc explorer, click on "Choose .psarc Directory" and choose your Rocksmith2014 directory.. wait for processing to finish and then click "Update songs owned"
- once update finishes go to dashboard and click refresh stats
- once stats are refreshed, you should see bunch of nice data in the dashboard
- let me know if encounter error in any of the above steps
![image](https://user-images.githubusercontent.com/5438703/47626809-31f2d380-daea-11e8-8c6f-3937101da47a.png)


The Steam OAuth option is used to update the owned/acquired date status for songs in Songs->DLC Catalog. If the above steps are working correctly, you can try going to Settings and signing in via steam and then going to DLC catalog and clicking the two buttons

"Update RS DLC Catalog" -> There should already be song dlc's in the view, to keep the list up to date press this button
"Update Owned/Acquired Data" -> If steam oauth worked properly, you can press this to fetch the owned/acquired info from steam

**Comment by Zoutje** [comment]
Thanks its working great now! Just one small problem is that in the owned songs category its counting songs that I don't own. I think they are from RS1, like Nickelback for example is there but I don't own those. I tried resetting the songs in the settings but they still show up. Its not a big deal, but it is a little annoying as it counts them as unplayed too even though I don't own them.

**Comment by sandiz** [comment]
> RS1, like Nickelback for example is there but I don't own those.

you can delete them manually by clicking on a row in songs->owned and clicking "Delete Songs from DB" button, they'll come back if you reimport though. I'll work on a setting to ignore certain tracks.. #30 
![image](https://user-images.githubusercontent.com/5438703/47635878-ad1caf80-db13-11e8-884d-871b28b6ebd2.png)

> you could filter the Rocksmith ingame songs lists

give setlists a go! more info here: https://github.com/sandiz/rs-manager/issues/23#issuecomment-431526194

sorry the documentation is all over the place rn, i am working an a in-app help section, which will have all the info rs-manager supports

**Comment by sandiz** [comment]
option to permanently ignore an arrangement added in [v1.2.5](https://github.com/sandiz/rs-manager/releases/tag/v1.2.5)
