### ISSUE TITLE
Duplicate arrangements

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#3]
![screen shot 2018-07-23 at 10 09 34 am](https://user-images.githubusercontent.com/1568662/43088954-b01692b4-8e60-11e8-9a14-5365d02e28a9.png)

- Some of those "Lead"s are "Alt Lead"s
- But there's also identical copies of each - 2 basses, 2 leads, 2 alt leads, 2 rhythms
  - Probably a result of me scanning the psarcs from multiple places in an attempt to get my library loaded
  - But uniqueness should be constrained based on the arrangement id - adding an already existing one should update, instead of creating new..

**Comment by sandiz** [comment]
good catch, i'll add unique constraint to the arrangment id

**Comment by sandiz** [comment]
fixed in `alpha5`

**Comment by JustinAiken** [comment]
Fix confirmed! Also fixed the search pulling in extra things :)
