### ISSUE TITLE
Setlist Issues

### ISSUE THREAD

**Issue by Zoutje** [sandiz/rs-manager#31]
Hey again,

Loving the quick updates. I tried using the ''Generated'' list for the request I had. However its not working as intended for me. I used Filter type; arrangement like lead and it shows rhythm. I also tried not like rhythm, but its still showing rhytm. 

Also I was wondering if it would be possible if there was a way to use filters in Rocksmith playlist (like from Rocksmith Song list 1) because I basically have all my tracks I like in that playlist. Would be great, if I just could filter to Lead then I have everything in one place. Otherwise I have a bunch of songs I don't really like in this list and its a bit of a nuisance to manually remove song by song.

**Comment by JustinAiken** [comment]
Oh yes, it seems like the Generated list has broken somewhere between 1.0.4 and the current... My "unplayed" standard tuning list used to have a few thousand, now it has 12:

![screen shot 2018-10-29 at 2 37 45 pm](https://user-images.githubusercontent.com/1568662/47678800-408fc800-db88-11e8-8032-9ecb6ca842f0.png)

I'll see if I can figure out where exactly something went wrong..

**Comment by sandiz** [comment]
>  I used Filter type; arrangement like lead and it shows rhythm. I also tried not like rhythm, but its still showing rhytm.

investigating... 

> if there was a way to use filters in Rocksmith playlist (like from Rocksmith Song list 1) because I basically have all my tracks I like in that playlist.

you can import your rs songlist from settings
![image](https://user-images.githubusercontent.com/5438703/47679131-b42dd700-db80-11e8-8203-05e4ca6438ba.png)
![image](https://user-images.githubusercontent.com/5438703/47679294-30c0b580-db81-11e8-8681-9773e2afef04.png)


it'll create a manual playlist for you. manual playlist only support song/artist/album filters for now (i can add an arrangement filter)

**Comment by sandiz** [comment]
@JustinAiken it might because of the this commit https://github.com/sandiz/rs-manager/commit/a88c91bc59fc52f924d66fd8d5962bb3c07462f0

i think i'll revert that commit, it's not doing what i intended..

**Comment by JustinAiken** [comment]
Yep that's it - if I pull down current `master`, `git revert a88c91b`, and rebuild, the generated setlist works again ✅

**Comment by sandiz** [comment]
thanks for confirming, i'll revert it in the next build

**Comment by sandiz** [comment]
![image](https://user-images.githubusercontent.com/5438703/47681612-30c3b400-db87-11e8-85eb-1ae69f4e6604.png)

>I used Filter type; arrangement like lead and it shows rhythm. I also tried not like rhythm, but its still showing rhytm

this is happening because some tracks are marked as combo and show up when you filter for "lead".. to remove them add another filter like so

![image](https://user-images.githubusercontent.com/5438703/47681949-2950da80-db88-11e8-93fa-ed63fc624855.png)

The "Combo" information is not shown currently, i'll explicitly display them in the next release

**Comment by sandiz** [comment]
some other rhythm tracks might sneak through because of wrong metadata. i am debating what to do in that case..

**Comment by JustinAiken** [comment]
> The "Combo" information is not shown currently, i'll explicitly display them in the next release

I kind of like just seeing "Lead" or "Rhythm" as it does in-game, instead of the "combo" craziness... 😉

**Comment by sandiz** [comment]
how bout an asterisk ?

**Comment by sandiz** [comment]
[v1.2.5](https://github.com/sandiz/rs-manager/releases/latest) has the revert fix
manual and rs generated setlists now support arrangement basic filter

@Zoutje  let me know if the info provided in the ticket works!

**Comment by JustinAiken** [comment]
> v1.2.5 has the revert fix

Does it? I don't see it in the history..

**Comment by sandiz** [comment]
oops, updated in [v1.2.6](https://github.com/sandiz/rs-manager/releases/latest)

thanks for looking out! 😄

**Comment by JustinAiken** [comment]
1.2.6 working great, thanks for the fixes!
