### ISSUE TITLE
Some requests/ideas around setlists in the sidebar

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#32]
- [Bug?] Sort them in alphabetical order, instead of the kind-of-random they are now
- [Bug?] If you have more setlists than fits on the screen, scrolling is wonky
- [Feature Request] Remember if "Songs" and "Setlist" were expanded when reopening the window
- [Feature Request] "Starred" or something setlists
- [Mega Feature Request] Setlist folders 
  - Can place setlists in folders
  - Which folders are expanded is also remembered

**Comment by sandiz** [comment]
>[Bug?] Sort them in alphabetical order, instead of the kind-of-random they are now
i think its sorted by rowid now 
>[Bug?] If you have more setlists than fits on the screen, scrolling is wonky
>[Feature Request] "Starred" or something setlists

good feedback! these three look straightforward. will work on them :+1:

**Comment by sandiz** [comment]
>[Feature Request] Remember if "Songs" and "Setlist" were expanded when reopening the window
>[Mega Feature Request] Setlist folders
Can place setlists in folders
Which folders are expanded is also remembered

bundling these two together, will look for a suitable tree component if not write one.
this will probably come after

**Comment by sandiz** [comment]
### Setlist TODO
#### P1
- [ ] Sort them in alphabetical order
- [ ] scrolling is wonky
- [ ] Starred setlists
#### P2
- [ ] tree view / folders 
- [ ] remember expand/collapse states

**Comment by JustinAiken** [comment]
New sidebar functionality is great! Much improved.. 
Only thing is there's too much padding at the bottom: 

![screen shot 2018-11-08 at 7 39 56 am](https://user-images.githubusercontent.com/1568662/48205630-c4d11080-e329-11e8-8471-12e3b9663465.png)

**Comment by sandiz** [comment]
i think its set at max-height: 285px, i'll make it a % instead so it flows well with taller resolutions

whats resolution is that ? 4k?

**Comment by JustinAiken** [comment]
> whats resolution is that ? 4k?

An LG ultrawide,  3440 x 1440

**Comment by sandiz** [comment]
hi @JustinAiken,
all the requested features should now be in master (8a5d053994a99f185933c7514ce6355d46f7d90b). I havent made any builds yet (windows testing is left), but you should be able to pull and build to get the latest and greatest.

the new setlist looks like so:
![image](https://user-images.githubusercontent.com/5438703/48589748-c2eeea80-e8f1-11e8-8e8b-8ae3cce7907e.png)

Closing the issue as fixed, please open/reope if you have any feedback/bug reports

thanks!

**Comment by JustinAiken** [comment]
Perfect! Setlist sprawl managed!
