### ISSUE TITLE
Feature Request songlists

### ISSUE THREAD

**Issue by Zoutje** [sandiz/rs-manager#33]
Hello,

I am a big fan of the RS manager. One thing that prevents it from being perfect for me is the setlists.
I am not sure what is possible coding wise, but I just give some things I like to see to make it perfect for me:

-Being able to add filters to Rocksmith Song lists (imported from in-game) 
-Individually able to add/delete arrangements to custom lists; Rhythm, Bass or Lead/Alt lead from tracks. Now if you add or delete you add or delete all arangements at a time. 
-A workaround that doesn't show Rhythm, but does show lead from RS1 songs, they are currently not showing because the ''combo'' arrangement.

Ultimately what I would love to see is a list that shows Lead songs that I like (that are currently in my RS Song list 1 playlist) so I can remove songs from the base game that I don't like. I currently have a goal of reaching 80% in all songs from my RS Song list 1 in the lead path. Both suggestions would enable me to keep perfect track of my goal. With custom lists I could manually add all Lead from songs I like **OR** with filters in imported RS lists I could filter out rhythm/bass. 

I hope I made clear what I would like to see as English isn't my first language. I am also not sure what is possible, I appreciate all the effort greatly.

**Comment by sandiz** [comment]
fixed in release [v1.5.5](https://github.com/sandiz/rs-manager/releases/tag/v1.5.5). 

Let me know if the fixes worked, thanks!
