### ISSUE TITLE
[Feature Request] Make plat/silver picks and gold/bronze more distinct

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#34]
**Is your feature request related to a problem? Please describe.**
It's kind of hard to tell which picks are which when glancing at them: 

![screen shot 2018-11-28 at 3 54 38 pm 1](https://user-images.githubusercontent.com/1568662/49187831-fdab4680-f325-11e8-885d-e68f6343a889.png)

Which is better? 
 - Is the 2nd from the top, or 3rd from the bottom a better playthrough?
- What about gold vs bronze? 
- I can't even tell!

**Describe the solution you'd like**
- Maybe differentiate the platinum and gold (and FC, since it's the best, even if it doesn't have conflicts) with kind of a crystalized effect, like in game:  

![screen shot 2018-11-28 at 3 56 54 pm](https://user-images.githubusercontent.com/1568662/49187929-47942c80-f326-11e8-943a-7b5cec264ed9.png)

**Describe alternatives you've considered**
- Or a halo? 
- Or make the silver/bronze really ugly, hahaha
- Or add nums/letters?

**Comment by sandiz** [comment]
ya i agree the icon sets right now are kinda underwhelming. i'll try to see if i can extract the images rs uses or find better ones on the internet.

let me know if you stumble onto a set you like

**Comment by JustinAiken** [comment]
> let me know if you stumble onto a set you like

Do they need to be svg or does png work as well?

**Comment by sandiz** [comment]
i can make them work with both, no issues there

**Comment by sandiz** [comment]
found these in static.psarc > gfxassets > libs - bronze/plat/-/gold/silver
![image](https://user-images.githubusercontent.com/5438703/49248823-77e3d580-f3cf-11e8-8b57-6b1313c02862.png)

what do you think of these ?

**Comment by JustinAiken** [comment]
Nice! Haha, I was just digging around the psarcs trying to find which one had those.  
You could put a greenish filter over the plat for the FC one

**Comment by JustinAiken** [comment]
Waaaaay better looking! Many thanks :) 

![screen shot 2018-11-29 at 6 03 37 pm](https://user-images.githubusercontent.com/1568662/49261875-25231180-f401-11e8-89c1-d8e64cb53e4e.png)

**Comment by sandiz** [comment]
haha you are fast! i was just about post a comment asking for feedback 😆

**Comment by sandiz** [comment]
fixed in [v1.5.7](https://github.com/sandiz/rs-manager/releases/tag/v1.5.7)
