### ISSUE TITLE
[FEATURE REQUEST] Sort order on setlists

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#35]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a new request... 

**Describe the solution you'd like**
- Instead of the songs owned list or the setlists always defaulting to mastery descending, make it customizable:
  - Globally
    - And then each setlist can have an option to use the global settings, or override
  - I think datatables lets you do multiple sorts; would be even better if you could pick 2 or 3 (ie, playcount descending, but in case of a tie order by difficulty ascending

**Describe alternatives you've considered**
- Continue just clicking on difficulty every time I open a setlist 😛 

**Additional context**
I'm opening a few issues here... if there's any you like the idea of, but don't want to do yourself, let me know and I'll take a stab!  Or if you don't like ideas feel free to reject 😄

**Comment by sandiz** [comment]
good idea! global one can go in `config` and setlist one can go in `setlist_meta`

i've to think of a way to allow multiple sort and single sort with the tables, maybe a multisort mode or something..

**Comment by sandiz** [comment]
fixed in [v1.5.9](https://github.com/sandiz/rs-manager/releases/tag/v1.5.9)

@JustinAiken let me know if it works!

**Comment by JustinAiken** [comment]
Absolutely perfect!
