### ISSUE TITLE
[FEATURE REQUEST] Notes

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#37]
**Is your feature request related to a problem? Please describe.**

It would be nice to see notes about a given track, and also to have an area to write personal notes about a track.

**Describe the solution you'd like**
- Arrangement notes
  - Something that's stored by arrangement_id in .csv or something that can be imported when adding arrangements from a psarc
  -  Has notes like "this is vocal melody transcribed for guitar" or other things that are true for everyone
  - PRs could help fill that out with data from TRR and such
- Personal notes
  - Where you can jot notes to yourself, like "Make sure to use ring finger instead of pinky in the last bar"

**Describe alternatives you've considered**
A big markdown file of notes locally 😜

**Comment by sandiz** [comment]
fixed in [v1.7.1](https://github.com/sandiz/rs-manager/releases/latest)

@JustinAiken let me know if the UX for notes works! open to all feedback and suggestions!

**Comment by JustinAiken** [comment]
> let me know if the UX for notes works! 
Really like the way both work! 

I'll try and add a bunch to the global csv sometime this or next week.
