### ISSUE TITLE
[Feature Request] rslive features

### ISSUE THREAD

**Issue by sandiz** [sandiz/rs-manager#38]
**Is your feature request related to a problem? Please describe.**
over on r/rocksmith discord, thejohnnewton shared some great ideas for future rocksmith. some of them might be possible now with rs-manager

**Describe the solution you'd like**
Sound capture (whole mix/possible to isolate ?)
track good and perfects with <1000ms accuracy
find timing data from psarc (?)

**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by sandiz** [comment]
while looking for static assets found this:
static.psarc->debug.commands.json 
```
	{
					"Name" : "Start Recording",
					"CommandOnSelected" : {
						"Command" : "DebugStartRecording"
					}
				},
				{
					"Name" : "Stop Recording",
					"CommandOnSelected" : {
						"Command" : "DebugStopRecording"
					}
				},
```
note: check with hopper if functions are still there or removed

**Comment by sandiz** [comment]
>Sound capture (whole mix/possible to isolate ?)

usb raw audio capture support in `raw-record`, outputs a raw file to the temp directory.
imo the raw sound is kinda underwhelming as its a clean tone with no filter. 

the mixed sound is better but its hard to record (node has bad crossplatform audio support) and is outside the scope of this app. `Audio Hijack`/`Total Recorder` are much better tools for recording audio from an app. 

>track good and perfects with <1000ms accuracy

fixed in `master`
>find timing data from psarc (?)

fixed in `master`

**Comment by sandiz** [comment]
![Screenshot](https://raw.githubusercontent.com/sandiz/rs-manager/master/screenshots/images/hit-percent-chart-guitar.png)

**Comment by sandiz** [comment]
![screenshot-bass](https://raw.githubusercontent.com/sandiz/rs-manager/master/screenshots/images/hit-percent-chart-bass.png)

**Comment by JustinAiken** [comment]
> imo the raw sound is kinda underwhelming as its a clean tone with no filter.

That's okay, can always reamp it later - including through way better tone sims than the game fx 👍 

> outputs a raw file to the temp directory.

- Would be cool if able to pick where to save files...
- And if metadata could be associated with it, so you could see that "some_wav.some_timestamp.wav" was say Gimme Shelter lead track 0:30-0:45 from 0:00-0:15 or the such...

**Comment by sandiz** [comment]
>That's okay, can always reamp it later - including through way better tone sims than the game fx 👍

oh yay, wasnt sure if it was useful. i'll polish the recording stuff and add your suggestions before pushing to master!

**Comment by sandiz** [comment]
>That's okay, can always reamp it later - including through way better tone sims than the game fx 👍

@JustinAiken what s/w would you recommend for this ? i am writing the help doc, will add it there

**Comment by JustinAiken** [comment]
> what s/w would you recommend for this 

- [BiasFX](https://www.positivegrid.com/bias-fx/) (often has a free version with a couple of amps)
- [Amplitube](https://www.ikmultimedia.com/products/amplitubecs/)
- [Revalver](https://revalver.peavey.com/)

Or you could use a DAW to reroute it through something like an AxeFX, Line6 gear, or even physical tube amps..

**Comment by sandiz** [comment]
rslive features are now  in https://github.com/sandiz/rs-manager/releases/tag/v1.8.0

>Speaking of... could there be an option to record whenever you're in-song, if RockSniffer/RSManager are both running? Like an e-version of a Line 6 Backtrack or Gibson Memory Cable

tracking this as a separate issue
