### ISSUE TITLE
Odd nested in sidebar w/ playlists

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#44]
**Describe the bug**
![screen shot 2018-12-28 at 4 39 28 pm](https://user-images.githubusercontent.com/1568662/50530890-8d781800-0abf-11e9-82c7-1742e6585b8e.png)

^^ Some playlists randomly end up "nested" under each other  ^^
All of those should be at the same level

**To Reproduce**
- Create a lot of playlists, put them in a folder

**Expected behavior**

This:
```
[ ] 
[ ] 
[ ] 
[ ] 
```

Not this:
```
 [ ] 
   [ ] 
  [ ] 
     [ ] 
[ ] 
```

😛 

**Desktop (please complete the following information):**
Mac, RS Manager on `master` (although has been around since the beginning) 

**Additional context**
Perhaps the scrollbar should apply to the whole sidebar, instead of just the setlists? You can always collapse the setlist section if unneeded, but the dual scrollbars work a bit wonky: 
![screen shot 2018-12-28 at 4 44 54 pm](https://user-images.githubusercontent.com/1568662/50530921-f3649f80-0abf-11e9-9310-57deaeb81619.png)

Might be related to the nesting, might not... 🤔

**Comment by sandiz** [comment]
does the weird nesting happen only inside a folder ? i'll try to repro and fix.. 

good catch with the dual scrollbar, looks super weird. will fix..

**Comment by JustinAiken** [comment]
Ohh may not be actual nesting, but if the title of the setlist is long it gets moved to the left of where it should be - try just naming a setlist something very long to repro; happens in folders and out, but is more visible in folders

**Comment by sandiz** [comment]
fixed in [v1.7.2](https://github.com/sandiz/rs-manager/releases/tag/v1.7.2)

**Comment by JustinAiken** [comment]
So much better looking!  

![screen shot 2018-12-31 at 7 06 35 am](https://user-images.githubusercontent.com/1568662/50561722-af91b600-0cca-11e9-9ed9-e15e05035539.png)
