### ISSUE TITLE
[MAC] Crashes on startup because of naudiodon

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#46]
**Describe the bug**
Crashes on running migration startup screen.. pulling up the dev tools console shows a stacktrace about naudiodon complaining about libportaudio.dylib not being loaded

**To Reproduce**
- Download the latest 1.7.2 release
- Start it on a Mac it wasn't build on

**To Un-Reproduce**
Building the same tag locally, it all works perfect. Looks like it might be related to this issue? https://github.com/Streampunk/naudiodon/issues/3

**Comment by sandiz** [comment]
@JustinAiken can you try https://github.com/sandiz/rs-manager/releases/tag/v1.7.3 and see if it fixes the issue.

uses naudiodon from github which has some extra fixes

**Comment by JustinAiken** [comment]
No luck I'm afraid 🙁 

![screen shot 2019-01-01 at 5 46 22 pm](https://user-images.githubusercontent.com/1568662/50577791-363eb400-0ded-11e9-901a-c0154c7f5628.png)

**Comment by sandiz** [comment]
i've updated the build, can you give https://github.com/sandiz/rs-manager/releases/tag/v1.7.3 a go again?

**Comment by JustinAiken** [comment]
Great success, crash fixed!
