### ISSUE TITLE
Better display of Arrangement type

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#5]
Instead of things like "Alt. LeadCombo", here's how to map the arrangement type to match what's displayed ingame:

https://github.com/JustinAiken/rsprogress_server/blob/779792f38f28131d07e95c7b726c2826021621e4/lib/arrangement_detailer.rb#L40-L56
  - In that code, `arrangement_properties` is just the data keyed behind `ArrangementProperties` in the manifest JSON

**Comment by sandiz** [comment]
the code reference is super helpful thanks! i didnt pay attention to the `ArrangementProperties` section before, i was blindly using `ArrangementName`

i'll also add tuning and capo data as well, the `TUNINGS` array is super helpful!

**Comment by sandiz** [comment]
fixed in [alpha5.2](https://github.com/sandiz/rs-manager/tree/alpha5.2)

arrangement name is now derived from arrangement properties matrix, similar to the one you had.
added tunings/capo/technique used info as well

**Comment by JustinAiken** [comment]
alpha 5.2 crashes on the setlist views for me, but looks like you already have fixes commited

**Comment by sandiz** [comment]
oh sorry about that, i updated the builds, [alpha5.3](https://github.com/sandiz/rs-manager/tree/alpha5.3)

**Comment by JustinAiken** [comment]
alpha 5.3 works great! Nice additions 👍
