### ISSUE TITLE
Flaky DLC import

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#57]
**Describe the bug**
The DLC setlist import skips some entries

**To Reproduce**
1. Go to Settings > Import RS Song List > Import DLC Packs as Songlist

**Expected behavior**
Every setlist/arrangement on the .csv gets imported

**Actual behavior**
Some (towards the beginning) get skipped

**Additional context**
If I add a `console.log(line)` in the line-by-line on-line handler, right after the `pause()`, here: https://github.com/sandiz/rs-manager/blob/4ec9e8af1c10874d47afcf28d7976c66528faa5d/src/Components/settingsView.js#L246-L249

then I see something odd:

```
2014-04-15,Garbage Song Pack,Garba2015-03-10,Jeff 2016-02-16,Hit Singles IV Song Pack,Sublime,Bad2017-02-07,80s Mix II Song Pack,Kenny Loggins,2018-01-16,Green Day III,Green Day,Boulevard Of Broken Dreams,ACB92D364223BF2006E596E0C5CC5298,0.64864864862019-04-02,Roxette,Roxette,Listen to Your Heart,46BDBE3E81B32C70E1548C835F048C36,0.50
2019-04-02,Roxette,Roxette,Listen to Your Heart,45926D85D0B3751A3FF0E2C71628FB0D,0.50
< .. on and on with lines that look okay .. > 
```

Each time I try, that first line is random garbled lines from further down the pack, and then all the lines that SHOULD be there follow - sometimes it skips a few dozen, but it finishes fine going down to the end of of the file.

Something to do with the line reader starting to slurp the stream... ¯\_(ツ)_/¯

**Comment by sandiz** [comment]
super weird, investigating..

**Comment by sandiz** [comment]
thanks for the report! fixed in [latest](https://github.com/sandiz/rs-manager/releases/tag/v2.0.3)

I am no longer seeing the garbage lines when i `console.log(line)`. not sure why it happened, but let me know if you still see weirdness
