### ISSUE TITLE
"Refresh Stats from Profile" Broken

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#59]
**Describe the bug**
Just updated from 2.0.5, to 2.1.1, and played some new songs. After hitting "Refresh Stats from Profile", it does lots of activity, but then nothing updates - the songs I played still show 0 plays and 0% instead of 1 play and 100%.

**To Reproduce**
- Be on 2.1.1
- Have some progress
- Hit "Refresh Stats from Profile"
- After much processing, nothing happens

**Expected behavior**
- Stats update on the Dashboard after react does it's thing
- Going to songs or a setlist should show the new progress

**Screenshot**

Also, looks like some of the badges have dissappeared:
![Screen Shot 2019-05-03 at 10 21 55 AM](https://user-images.githubusercontent.com/1568662/57151095-4f507500-6d8d-11e9-9301-8a1c05a6a16f.png)

All those blank spaces should either be a platinum, gold, or fail

**Desktop (please complete the following information):**
 - OS: MacOS10.13.6
 - Version: 2.1.1

**Additional context**
I'd installed rsrtools via pip3 and linked the binary in the new settings, but haven't touched anything with it yet.

**Comment by JustinAiken** [comment]
Just tried b57fdf2edd56d480a1fb60341f51a76e5dd7aedf since it seemed the most likely place for it to have broke, but it works there.. somewhere between there and 0bd8562e991076778b29042b5a8fd522c8c9349d is where it went wrong...

**Comment by sandiz** [comment]
aah i think i know what happened, i added caching to readProfile and it might be reading the old cached data
https://github.com/sandiz/rs-manager/blob/master/src/steamprofileService.js#L31

fixing, thanks for the report!

**Comment by sandiz** [comment]
@JustinAiken can you try latest master whenever possible, should fix the issue ?

i'll release a recovery build once i am done with #58

**Comment by JustinAiken** [comment]
Yep, just tried ac8c80a3bc11d1834033a2561a9c1021609af2a8 and it works. 
Thanks for the quick fix!
