### ISSUE TITLE
Songs count is incorrect

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#6]
It doesn't take into account songs with the same title, but different bands.  

For example, `Know Your Enemy` is the title of two songs (Green Day and RatM), but counts as only 1 song.  This is clear from the search results:

![screen shot 2018-08-07 at 11 25 59 am](https://user-images.githubusercontent.com/1568662/43792049-cb1ff4b2-9a34-11e8-9f74-2887d39b6656.png)

But besides the search results also throws off the "Songs Owned" stat and I'm guessing a few others

**Comment by sandiz** [comment]
good catch Justin!
happening because of this distinct
` SELECT count(*) as acount, count(distinct song) as songcount`

`(distinct artist)` makes more sense

**Comment by JustinAiken** [comment]
`count(distinct song || artist)` should do it

**Comment by JustinAiken** [comment]
Also, a few `artist` names are sort-of-duplicated because of casiness: 

```sql
SELECT 
   DISTINCT(artist) 
FROM songs_owned 
WHERE artist LIKE "A%20Day%"

-- A%20Day%20to%20Remember
-- A%20Day%20To%20Remember
-- "To" vs "to"
```

**Comment by sandiz** [comment]
```
sqlite> select distinct songkey, song from songs_owned where song like "%know%20your%20enemy%";
GreeKnow|Know%20Your%20Enemy
RageKnow|Know%20Your%20Enemy
```
distinct on `songkey` seems to do the trick, should also prevent the artist duplication.

try out the [latest release](https://github.com/sandiz/rs-manager/releases/latest) and let me know if it fixes the issue!

**Comment by JustinAiken** [comment]
Yep, that fixes it!
