### ISSUE TITLE
[Feature Request] Find Steam account/Rocksmith profiles by name

### ISSUE THREAD

**Issue by BuongiornoTexas** [sandiz/rs-manager#60]
Hi Sandi,

A **low priority** feature request as discussed yesterday.

Cheers,

Larry

**Is your feature request related to a problem? Please describe.**

Rather than asking the user to find their Rocksmith profile file, it would be good to provide menus that allow the user to select a Steam account by name, and then their Rocksmith profile by name.  This would help people who don't understand (or don't want to understand) the layout of their Steam files, and would help reduce selection mistakes for people with multiple accounts/profiles. It'd also help people like me who are lazy (and have multiple accounts and profiles :-) ).  

**Describe the solution you'd like**

I tried a couple of paths in rsrtools - the following approach is what I found best:

1. Find the steam folder (``~Library/Application Support/Steam`` for OS X, or from the registry
   key ``HKEY_CURRENT_USER\Software\Valve\Steam\SteamPath`` for Windows). 

2. Read the loginusers.vdf file in the ``<steam path>/config`` directory. This gives you
    the following information for each account that has logged in locally:

             - 17 digit steam user id.

             - Account name.

             - Publlic account alias (persona name)

   (This is where I ran into the unreliable case problem with the dictionary keys.)

3. Ask the user to select an account by name  or alias.

4. Convert the 17 digit id into a steam account id (which is also the the name of the users folder
    under ``<steam path>\userdata`` by grabbing the low 32 bits of the steam user id:

                account_id = user_id & 0xFFFFFFFF

5. Load ``LocalProfiles.json`` for the selected account id.

6. Ask the user to select a Rocksmith profile by name from the names available in 
   ``LocalProfiles.json`` (and consequently also select the ``_PRFLDB`` file).

**Describe alternatives you've considered**

I tried a couple of options around searching Steam folders - the option described above seems to be the best for getting to the desired result even if it is a bit round about.

**Additional context**

None. It's really a usability request for people who are guitar rather than computer focused.

**Comment by sandiz** [comment]
added interactive profile selection in [v2.1.5](https://github.com/sandiz/rs-manager/releases/tag/v2.1.5)

@BuongiornoTexas  thanks for the tips, they were super helpful! definitely much more user friendly with the new profile selection 😇

**Comment by BuongiornoTexas** [comment]
Nice work! Thanks for implementing it (and amazing turn around as well).
