### ISSUE TITLE
reddit thread feedback

### ISSUE THREAD

**Issue by sandiz** [sandiz/rs-manager#72]
- [x] add first time wizard for new users (needs #64)
   - select profile/dlc path (possible to autodetect dlc path ?)
   - import and refresh stats in  one go

- [x] add website
   - github is complicated for new users to navigate
   - create static website using gh-pages

- [x] drag-drop
  - songs owned to setlists
- [x] localization 
  - fr (mvp, using google translate)

src: https://www.reddit.com/r/rocksmith/comments/bv0a6z/anyone_played_around_with_rocksmith_manager_it/

**Comment by BuongiornoTexas** [comment]
Hi Sandi,

I'm not sure if it will be useful or not, but rsrtools has a routine for autodetecting Rocksmith location/dlc path. Again a wander through the Steam .vdf files. 

In case it is relevant, the code snippets are in rocksmith_path and db_entries in scanner.py. (I can put together a gist tomorrow if it'd be useful).

Cheers,

Larry

**Comment by sandiz** [comment]
oh sweet, that should come in handy!

many thanks 🙇

**Comment by sandiz** [comment]
all tasks complete
