### ISSUE TITLE
2.4 breaks "Refresh Stats" button

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#83]
**Describe the bug**

- When hitting "Refresh Stats from Profile", I get this error: 

![Screen Shot 2019-10-03 at 3 53 18 PM](https://user-images.githubusercontent.com/1568662/66166975-0e87b100-e5f6-11e9-806a-ef49bab4ebad.png)

and the new Toast thing spins forever: 

![Screen Shot 2019-10-03 at 3 53 14 PM](https://user-images.githubusercontent.com/1568662/66166983-16475580-e5f6-11e9-8646-c009cd26d1d7.png)

**To Reproduce**
- Be on the just released version 
- Hit said button

**Expected behavior**
- Toasty notification should talk about how fast it's importing things :D 

**Desktop (please complete the following information):**
Mac OS

**Comment by sandiz** [comment]
looking.. thanks for the report

**Comment by JustinAiken** [comment]
Here's a better stacktrace from running it in dev mode instead of the packaged `.dmg`:

![Screen Shot 2019-10-03 at 4 03 20 PM](https://user-images.githubusercontent.com/1568662/66167446-6246ca00-e5f7-11e9-9f54-1e5439f74832.png)

**Comment by sandiz** [comment]
pushed a fix and started a build... looks like the key may or may not be there so i added a bunch of checks to all the stats refresh routines.. let me know if it works 😇

**Comment by JustinAiken** [comment]
No luck looks like 😞 

Now it's `Unhandled Rejection (TypeError): Cannot use 'in' operator to search for 'TimeStamp' in undefined`

![Screen Shot 2019-10-03 at 4 16 23 PM](https://user-images.githubusercontent.com/1568662/66167995-2876c300-e5f9-11e9-93c2-b43199f88509.png)

**Comment by sandiz** [comment]
oh! added a null/undefined check in bbd816b2,  give that a go when you get a chance!

**Comment by JustinAiken** [comment]
That works! 

...and is speeeedy! 🚀
