### ISSUE TITLE
Request - Tags on arrangements

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#86]
- Add ability to create user tags 
  - Tags can act/function similar to the tags in DLC Catalog
  - But really cool if you can pick colors too - neutral color for something like `fingerstyle`, red for `dammit_keep_missing_one_freaking_note`, etc... 

- Can add tags to arrangements in the detail view 
  - Per-arrangement instead of per-song, since something like `fingerstyle` may only apply to the arrangement, not the song as a whole

- Can see tags for songs when just looking at the songs owned or a setlist view (just like they're immediately visible in the DLC Catalog table)

- Can filter tags in setlist options
  - Usage examples:
    - So you could quickly pull together say, a list of anything tagged `practicing_now` in a set of tunings for a given guitar
    - Pull up a list of songs tagged `fingerstyle` when you can't find where all your picks have disappeared to

**Comment by sandiz** [comment]
fixed with [v3.0.2](https://github.com/sandiz/rs-manager/releases/tag/v3.0.2). let me know if have any feedback or run into issues..

**Comment by JustinAiken** [comment]
I love it! =)
