### ISSUE TITLE
[BUG] Playlist stats broken

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#95]
**Describe the bug**
No stats are loadable for any setlist

**To Reproduce**
1. Go to a generated playlist
2. Click on the view stats modal
3. You'll see something like:

![Screen Shot 2019-11-23 at 11 28 02 AM](https://user-images.githubusercontent.com/1568662/69483410-53ed8100-0de4-11ea-8fac-31847d3f62eb.png)

No matter how many songs are on the list.

**Expected behavior**
You get a stat breakdown.

**Additional context**
I `git bisect`'d the problem to commit fb2b2d077755cd33d8e59d07271425b5a04d1a94 
I think the join is stripping out any songs without tags

**Comment by JustinAiken** [comment]
Yes, looks like the problem is in https://github.com/sandiz/rs-manager/blob/fb2b2d077755cd33d8e59d07271425b5a04d1a94/src/Components/setlistOptions.js#L128-L129 

For my simple "bass" setlist that is just all bass tracks that aren't CDLC I end up with this SQL:

```sql
SELECT 
  *,  
  GROUP_CONCAT(song_tags.tag, '|') AS tags FROM songs_owned  
LEFT JOIN song_tags using (id) 
WHERE arrangement LIKE '%bass%' 
AND is_cdlc IS 'false' 
```

Which only returns the single track with a tag.  If I try running it without the tags stuff: 
```sql
SELECT * FROM songs_owned
WHERE arrangement LIKE '%bass%' 
AND is_cdlc IS 'false' 
``` 

I get the full result set.  

This only seems to be a bug with the full load - the count-only function works okay:

```sql
SELECT 
  COUNT(*) AS acount, 
  COUNT(DISTINCT songkey) AS songcount 
FROM songs_owned  
LEFT JOIN song_tags USING (id) 
WHERE arrangement LIKE '%bass%' 
AND is_cdlc IS 'false' 

-- ^ returns the expected counts
```

**Comment by sandiz** [comment]
looking into this as soon as possible..

**Comment by sandiz** [comment]
thanks for the initial legwork on this @JustinAiken 🙇 , pushed a fix in this [release](https://github.com/sandiz/rs-manager/releases/tag/v3.0.4). let me know if you are still seeing the issue!

**Comment by JustinAiken** [comment]
Uh-oh... can't tell if it fixed it or not.  Upon startup, I get this: 

![Screen Shot 2019-11-25 at 9 23 57 PM](https://user-images.githubusercontent.com/1568662/69599335-eac76280-0fc9-11ea-841f-2d8595c98550.png) 

in the inspector.  And in the main window, it just loads the background.

**Comment by sandiz** [comment]
oh weird! I moved `cross-spawn` to dependencies and pushed the fix [here](https://github.com/sandiz/rs-manager/releases/tag/untagged-dd83334d2366cadb4efd). let me know if that works

**Comment by JustinAiken** [comment]
Confirmed fix!

![Screen Shot 2019-11-26 at 7 30 50 AM](https://user-images.githubusercontent.com/1568662/69642270-bc27a700-101e-11ea-9f6b-fd384a0a173f.png)
