### ISSUE TITLE
rs-live & mojave 64 bit

### ISSUE THREAD

**Issue by sandiz** [sandiz/rs-manager#96]
from https://www.reddit.com/r/rocksmith/comments/ef9o7f/help_with_rocksmith_manager_live_on_macos/

Seasons Greetings everyone and a couple of questions for anyone using Rocksmith Manager (highly recommended) on MacOS.

I have been using the application for a few months and love it, but have never been able to get the live tracking to work. I allow incoming connections when starting the app and provide my administrator password when I click start tracking and see current song go to N/A.

I start Rocksmith - play a song and -- nothing. The current song pane never updates and I never see any data.

I am using Rocksmith Manager v3.0.4 on Majave 10.14.6. Any troubleshooting ideas?

A second, less annoying issue is that I can no longer get it to update my DLC acquired dates, which worked in an older version. It shows "Error fetching history (session expired), please login with Steam again!" - I go to Settings login (see a page show "Logged in" and no change.

Thanks.

**Comment by sandiz** [comment]
1. rs-live issues might be:
    a. mono gac rebuild
    b. mojave memory layout might be different (need to verify)
2. dlc acquired date might be
    a. steamID not saved? need to see config.json

**Comment by JustinAiken** [comment]
> b. mojave memory layout might be different (need to verify)

With the newest update making the jump to 64 bit, I would have been shocked if RSLive had kept working...

**Comment by sandiz** [comment]
oh, good point.. that's probably it

**Comment by mbagsh55** [comment]
Sorry guys, I should have mentioned in the original post that I am running the 64-bit version of Steam and Rocksmith.   I believe the dlc acquired date which worked previously was based on the dates before the Rocksmith 64-bit beta as well, so possible both issues relate to the 64-bit change.

**Comment by sandiz** [comment]
dlc issue/steam login not working is fixed with [v3.0.5](https://github.com/sandiz/rs-manager/releases/tag/v3.0.5), let me know if that works!

**Comment by mbagsh55** [comment]
Thanks @sandiz, I can confirm the dlc updates works perfectly now -- thank you

**Comment by sandiz** [comment]
this is blocked until cheatengine for mac 7.0 is [released](https://www.patreon.com/posts/what-im-working-29439869). the current tool that we use for mac (Bit Slicer) is no longer giving valid results when pointer scanning

**Comment by sandiz** [comment]
this should be fixed in [v3.0.10](https://github.com/sandiz/rs-manager/releases/tag/v3.0.10).  pls reopen if you run into issues.

thanks to @cheat-engine for releasing cheat engine 7.0 for mac!
