### ISSUE TITLE
Stats updating almost continously when using Rockstar Live tracking

### ISSUE THREAD

**Issue by GeePee29** [sandiz/rs-manager#97]
**Describe the bug**
Just upgraded to v3.0.5
In Rocksmith Live when using Tracking option, stats keep on updating. Often stats will start updating before the last stats upgrade has finished (see screen shot)
![2019-12-26](https://user-images.githubusercontent.com/51228703/71474319-d518a900-27d2-11ea-8ec3-5b6fef0b9886.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox. Firefox was not running when this problem occurred.
 - Version 71.0

This would not really be an issue for me if it wasn't for the refresh window(s) continually popping up and distracting me from my playing, which is already quite bad enough.

**Comment by sandiz** [comment]
thanks for the report, working on a fix..

**Comment by sandiz** [comment]
fixed in [v3.0.6](https://github.com/sandiz/rs-manager/releases/tag/v3.0.6). let me know if you are still seeing this issue

**Comment by GeePee29** [comment]
Cannot answer your question as I cannot get the new version to pickup any
of my songs in Rocksmith Live. Everywhere else seems to show them all OK.
Profile setup all looks good and I have also been into psarc explorer and
reset DLC directory path.

Any suggestions? TIA

**Comment by sandiz** [comment]
hmm thats not good, investigating..

**Comment by sandiz** [comment]
hi @GeePee29, give [v3.0.7](https://github.com/sandiz/rs-manager/releases/tag/v3.0.7) a go. should be much stable now!

you can try these troubleshooting steps when songs dont show up in rs live:
1. make sure the song is already imported
2. go to main menu in rocksmith and then restart tracking
3. if that fails, restart rocksmith and then restart tracking

**Comment by GeePee29** [comment]
Hi Sandi

I've installed 3.0.7
Initially Rocksmith Live did not detect songs but restarting Stats Manager
and RS2014 has fixed the problem. BUT...... it will only detect DLC, CDLC
and the RS1compatibility songs. It does not detect the original songs that
come with RS2014.

I don't know if this makes a difference but stats manager is located at
C:\Program Files\Rocksmith.Manager

RS2014 is located on a different drive
E:\steamgames\steamapps\common\Rocksmith2014

I had this problem when I first tried out your program and someone told me
to use psarc explorer to manually add the songs.psarc file which fixed the
problem. I tried this again today and it no longer fixes the issue.

**Comment by sandiz** [comment]
thanks for the report @GeePee29, i'll investigate. ideally adding songs.psarc should have fixed the issue...

**Comment by sandiz** [comment]
songs from songs.psarc are working for me.  only reason i can think of is somehow songs.psarc entries didn't get added to the library. when importing make sure that you are adding them to library by pressing "Update Songs > Owned" in psarc explorer after opening songs.psarc

![Capture](https://user-images.githubusercontent.com/5438703/71549151-7c314800-296d-11ea-828b-b1d16158c1fe.PNG)
![Capture2](https://user-images.githubusercontent.com/5438703/71549154-7d627500-296d-11ea-8db0-1fcd46e15d7f.PNG)

**Comment by GeePee29** [comment]
Working now thanks. I hadn't pressed the update button.
