### ISSUE TITLE
Save screenshot no longer creates a PDF on MacOS

### ISSUE THREAD

**Issue by mbagsh55** [sandiz/rs-manager#98]
Previous versions of RS Manager would generate a PDF when save screenshot was clicked from the infographic.   With the latest version when clicking I only see a scrollbar added to the image.

**To Reproduce**
1. From the Dashboard view click on "generate infographic"
2. Click on "go"
3. When the infographic is displayed scroll to the bottom and click "Save Screenshot"
(scroll bars are added to the view)

**Expected behavior**
Previous versions produced a PDF that from memory opened

Tested on MacOS Mohave [10.14.6]
RS Manager v3.0.7

**Additional context**
A second minor point is that both 'filler bars' for songs played and total songs are shown in white.   This may be by design but a different color for one bar (like orange is used for songs mastered) is easier to see.

Thanks

**Comment by sandiz** [comment]
fixed in [v3.0.9](https://github.com/sandiz/rs-manager/releases/tag/v3.0.9). adjusted the progress bar color, let me know what you think!

![image](https://user-images.githubusercontent.com/5438703/72507787-663ed680-37f9-11ea-9c7b-5b7164b59949.png)
